### ISSUE TITLE
Introduce top-level container

### ISSUE THREAD

**Issue by michael** [substance/scientist#15]
Should we think about introducing a top-level container (e.g. turning article node into a container node). That way the the body, back, etc. elements become accessible as an isolated node. E.g. select body node and review/change attributes.

**Comment by michael** [comment]
Just activated caption editing. However the clicking-through seems to be broken for inline isolated nodes.  The focus gets lost immediately. @oliver---- can you check?

**Comment by oliver----** [comment]
I don't think that this is necessary.
