### ISSUE TITLE
Add bibliography management to the editor

### ISSUE THREAD

**Issue by michael** [substance/scientist#16]
We are evaluating options to integrate bibliography management into the editor, including changing a reference, adding a new reference (e.g. via pasting a BibTex entry, or a crossref search).

Juan, Alex: I wonder how typically those ref-list elements look like in articles you process in OJS. Can you provide some examples?

We can not easily build interfaces for all possible variations that JATS supports (`<element-citation>`, `<mixed-citation>`, `<citation-alternatives>`, ...) so I'd suggest that we decide on a concrete tag structure that the editor will produce when a new reference is added. Ideally it's the same that the word conversion outputs.

Technically we want to map only ref elements to the Substance document model, and store the full xml string there. That way we have a good break out scenario, as you can always add the xml of a ref entry in a code editor. However if the structure matches to what we decide to support first-class we can show a visual interface and you can make fixes there.

**Comment by axfelix** [comment]
Here's an example of a reference output by our stack:

`<ref id="R1"><element-citation><person-group person-group-type="author"><name><surname>Anderson</surname><given-names>NicolaC</given-names></name><name><surname>Bischof</surname><given-names>WalterF</given-names></name><name><surname>Laidlaw</surname><given-names>KaitlinEW</given-names></name><name><surname>Risko</surname><given-names>EvanF</given-names></name><name><surname>Kingstone</surname><given-names>Alan</given-names></name></person-group><article-title>Recurrence quantification analysis of eye movements</article-title><source>Behav Res</source><year>2013-jan</year><fpage>842</fpage><lpage>856</lpage></element-citation></ref>`

I think currently we always output `<element-citation>` (which we get back from the CrossRef DOI lookup API when possible, though I don't think we get it back as XML -- that's our own transformation if I'm not mistaken).

**Comment by jure** [comment]
Hmm, interestingly enough, I've always used the `mixed-citation` element, though it would be very hard for me to answer as to why :) Is there a catch-all element in JATS for citations?

**Comment by axfelix** [comment]
I believe we were using mixed-citation up until recently but we started failing some validation checks when Erudit looked at the XML, so I made the change. It's probably a case of soft deprecations more than anything else but don't quote me on that.

**Comment by michael** [comment]
Thanks for the example. Very helpful! So if we temporarily optimized for ref elements that contain exactly one element-citation that would work with most of the content?

Again, you will still be able to edit files that contain multiple elements inside one ref but those would be accessible only via an XML code editor.

**Comment by axfelix** [comment]
Yes -- all of the ref elements we're currently producing contain a single element-citation.

**Comment by michael** [comment]
Closing in favor of #60 #59 #58 .
