### ISSUE TITLE
Renderer for ref entries

### ISSUE THREAD

**Issue by michael** [substance/scientist#18]
We need a rendering component for `<ref>` elements. Essentially this means mapping from XML to HTML for display. So the challenge here is to support as much as possible different JATS inputs so this works well with any JATS compatible file. 

Still we should allow to provide  custom renderer here if a publisher wanted to render bib entries differently.

**Comment by michael** [comment]
@axfelix have you done anything related to that task already for OJS? The challenge is to map any possible valid JATS XML representation to HTML so it's nicely displayed.

**Comment by axfelix** [comment]
Right now, our JATS XML -> HTML reference conversion is https://github.com/pkp/xmlps/blob/master/module/HtmlConversion/assets/html.xsl, then we use pandoc-citeproc to style the output with CSL.

**Comment by michael** [comment]
Interesting. Would be nice to use something existing that already works. However ideally we could do that all client-side so no server-roundtrip is needed. Maybe we can utilize the xsl stylesheet from the browser (afaik Chrome can do that) and maybe citeproc.js.

So this rendering is actually a task that we could need help with. Is that something PKP or Erudit could possibly take over if we provided all needed entry points?

**Comment by axfelix** [comment]
The XSL is by no means perfect! @giotta, what do you think? Of interest to your team?

**Comment by michael** [comment]
@jure did a first pure JS based take on this. Definitely needs to be improved but we have a basic renderer in place now. See https://github.com/substance/scientist/pull/26
