### ISSUE TITLE
How should we approach backmatter in author mode?

### ISSUE THREAD

**Issue by michael** [substance/scientist#28]
So backmatter / references etc. are missing in the author currently. We should have things more strict here. I think we don't really need a back matter that's just another container with sections etc. Instead we should just display a single ref-list at the bottom of the doc that's in a fixed place.

The main question is how we should approach conversion here. E.g. if the original JATS file has multiple ref lists and some stuff in sections in the backmatter.... If we really don't want to teach the author backmatter stuff in favor of a simpler interface it would be an option to really just normalize (=strip that content) during conversion. @oliver---- what's your opinion here? Is it worth investing into a loss-free conversion if many parts are not even accessible through the interface.

**Comment by oliver----** [comment]
I think in general we should figure out where JATS is too flexible from the/our authoring point of view.
E.g. we would only have one ref-list in the authoring tool.

Then the question is which ref-list to edit if more than one are present.
I think we should just pick the first and edit it.
Conversion is not really affected here, as everything is still regular JATS.

What we eventually do to 'normalize' the mult-ref-list case I don't know yet. I would need to understand first why somebody wanted multiple ref-list.

**Comment by oliver----** [comment]
Definitely we don't want the whole <back> free form in the author.
It would be more like having different UIs, such the References section, which are written into the back matter.

**Comment by oliver----** [comment]
The same for `<front>`.

**Comment by michael** [comment]
Solving this with overriding the ArticleComponent for the author.
