### ISSUE TITLE
Implement attribute editor for any element

### ISSUE THREAD

**Issue by michael** [substance/scientist#65]
We want to make all XML attributes editable through the editor. There will be a button "edit attributes" available from the XML navigation bar (see #30). However the question is how we are going to make a good UI for attribute editing.

Simplest to implement would be plain text editing and just to expose the XML code. The following sketch shows the first few child elements to give some context. Note that we need to find a way to preview the contents of all possible elements.

- Should we display all content? That could get pretty big (e.g. when you edit a top level section)
- We could display always the first 3 child elements and look no deeper
- On the other hand would it be useful to be able to edit the child tags right from the editor? (this may be possible re-importing a sub-tree and rerendering the node being changed)

![image](https://cloud.githubusercontent.com/assets/2931/16838934/6a8b57f0-49cc-11e6-8b26-8dd7fee38195.png)

Any thoughts on this? This is a bigger missing part to make the editor 'complete'.

**Comment by michael** [comment]
If you agree with that approach, I would suggest we use the same strategy for `<ref>` elements.

**Comment by axfelix** [comment]
As an initial reaction, I don't think we should display _all_ child elements when editing a node's attributes, but let me just clarify ... is the reason to display child elements and not just attributes when in this view because many of those wouldn't necessarily be visible from the WYSIWYG view, so it's possible that some nested children would be inaccessible to the editor otherwise? In that case, I'd say it might be OK to hardcode only displaying one or two _levels_ below the element you're editing rather than only a certain number of elements, and see if that handles most of the use cases...

**Comment by michael** [comment]
Generally it was meant just for contextual purposes (so the user realizes what element they are looking at). All the deeper content is accessible through the editor, with some exceptions: For `<ref>` and `<contrib>` elements we store the raw xml content instead of implementing all child nodes. That's simply a pragmatic approach, since their structure can vary quite much. So we allow editing of the full XML in those cases (for the publisher mode). In author mode we expose simple forms but with limited functionality.

For rendering we map XML to HTML for those nodes: https://github.com/substance/scientist/blob/develop/packages/jats/ref/refToHTML.js

**Comment by michael** [comment]
I will start with showing attributes only and just show '...' for the content. 

```xml
<sec
  id="s2"
  sec-type="datasets"
>...</sec>
```

We can see how it works and improve later. Our goal is to expose all XML to the editor in some way, so you don't have to switch to a text editor to access certain elements.

**Comment by michael** [comment]
That's done now.
