### ISSUE TITLE
Edit contrib elements

### ISSUE THREAD

**Issue by michael** [substance/scientist#66]
We need a way to edit `<contrib>` elements. I would suggest as a first step we should provide XML editing of such elements, so there are no limitations on the structure.

![image](https://cloud.githubusercontent.com/assets/2931/16839276/940e6ea8-49ce-11e6-9fdf-c99891776d3c.png)

For the author mode we can provide a visual form for editing but with limited functionality. E.g. only filling in the name element with surname and given-names. Handling affiliations etc. is a too complex task for the author mode I think. What we could do is just provide the bio element, where any additional info about the author can be stored.

**Comment by axfelix** [comment]
For an initial release, until we get more users wanting to back a more complex metadata editor (since I expect that will happen eventually) I think I'd be OK with four plaintext fields: surname, given-names, email, affiliation. There are a number of valid ways to do affiliation in JATS, and the (1,2) superscript approach is definitely superior, but it does support just having a single string as a child of each contrib.

**Comment by michael** [comment]
In order to provide a form editor we would need to detect a certain 'supported' element structure. So I'd suggest if the following properties are true we can display the form editor, if not, we fall back to an XML editor.

- there is exactly one name element that has surname + given-names
- there are no xref elements inside contrib

We can display form editors for each `<aff>` `<email>` element we find. If affiliations are realized via xrefs it will be hard to provide a form editor (and to manage the affiliations, delete add, edit, etc.)

However I guess the first step will be the XML editor + an XML to HTML rendering component.

**Comment by michael** [comment]
First iteration done. We may want to introduce a better XML editor that supports syntax-highlighting, code-folding etc. but that needs an evaluation of the editors out there.

![contrib-editing](https://cloud.githubusercontent.com/assets/2931/16875072/9a86c918-4a9d-11e6-8e9c-f2d513f7678d.gif)

**Comment by michael** [comment]
Done.
